### ISSUE TITLE
Plugin calls ucm on Windows instead of ./ucm

### ISSUE THREAD

**Issue by bytesource** [unisonweb/vscode-unison#10]
Hi,

When opening a folder containing `ucm` with this plugin, a terminal opens inside VS Code running this code:

// Plugin just calls `ucm` on Windows, which fails:
``` bash
ucm
bash: ucm: command not found
```

However, on Windows, I need to run `ucm` like this:

// This is what I did 
``` bash
./ucm
Now starting the Unison Codebase Manager (UCM)...
```
Is there a way to adapt the startup process, so that `./ucm` is called on Windows?

**Comment by ChrisPenner** [comment]
<img width="582" alt="image" src="https://github.com/unisonweb/vscode-unison/assets/6439644/d8cb94a8-aa3a-4728-a70c-9bdbeb23913e">

**Comment by bytesource** [comment]
Now everything is working perfectly. Thanks for pointing me to this setting!
