### ISSUE TITLE
floating point numbers inside strings...

### ISSUE THREAD

**Issue by stew** [unisonweb/vscode-unison#15]
Messes up the end of string detection. so in something like:

>  "0.0" ++ "1.1" 

it colors ` ++ ` as inside a string, and the two floating point numbers as being outside strings.

**Comment by ChrisPenner** [comment]
Do you mean in the parser, the Vim syntax highlighter, the VSCode plugin? Something else?

**Comment by ChrisPenner** [comment]
I think Rúnar must've fixed this as part of his syntax patches because I can't reproduce :) 
Let me know if you still can.
