### ISSUE TITLE
LspProcessingLog (MissingHandler False SCancelRequest)

### ISSUE THREAD

**Issue by clojj** [unisonweb/vscode-unison#2]
Maybe I was late to your fantastic dischord session and you mentioned that message (?)
It keeps popping up with a fresh installation of vs code 1.70.2 + ucm form the specified branch, for example when hovering over a term.. the type is shown successfully though.

ucm shows this btw
![image](https://user-images.githubusercontent.com/4367963/187779885-45f0a4f5-30b4-4d27-89ca-2550f5664eda.png)

**Comment by ChrisPenner** [comment]
Thanks! This should be fixed on latest UCM trunk 🙌🏼
